### PR TITLE
Loading svg on build from file

### PR DESCRIPTION
**Pull request by gewlar**
Don't know if that is what you had in mind, but this loads the svg from an external file.

It isn't perfect either, as the used plugin requires a fixed string as input. I could maybe rewrite the plugin to improve this functionality further.

### CODE REVIEW

**Comment by XYQuadrat** [comment]
Seems quite nice. The build currently fails since the package-lock.json wasn't updated accordingly with the package.json. Would be great if you could quickly change that.

(Side note: The new .svg can probably only be sensibly edited in Adobe Illustrator or similar; Inkscape doesn't support the CSS variable spec yet. But it's still nice to move the markup into a separate file IMO.)

**Comment by gewlar** [comment]
As the svg is still fully included in the final output, I can investigate the possibility to style svg parts on their own with css. Maybe those variables can be moved to a separate css file.

**Comment by XYQuadrat** [comment]
I think that might complicate things more than it would help. I doubt we'll edit the logo all that often, so that's not that big of a problem right now. If you agree I'll merge this in the current state.

**Comment by gewlar** [comment]
It certainly would add more files to the repo. As far as the logo doesn't change every other day I would leave it be for now.

**Pull request merged**
